### ISSUE TITLE
Bug: missing file

### ISSUE THREAD

**Issue by NizarBlond** [wangshijun/generator-angular-cordova#1]
Hi, when setting up the scaffolding, in the end of the process I fail due to this error:

...
[?] Which modules would you like to include?

C:\Users\Blond\AppData\Roaming\npm\node_modules\generator-angular-cordova\node_modules\yeoman-generator\lib\actions\actions.js:194
    throw new Error('Unable to read "' + filepath + '" file (Error code: ' + e
          ^
Error: Unable to read "C:\Users\Blond\AppData\Roaming\npm\node_modules\generator-angular-cordova\templates\common\index.html" file (Err
or code: ENOENT).
    at Generator.read (C:\Users\Blond\AppData\Roaming\npm\node_modules\generator-angular-cordova\node_modules\yeoman-generator\lib\acti
ons\actions.js:194:11)
    at Generator.readIndex (C:\Users\Blond\AppData\Roaming\npm\node_modules\generator-angular-cordova\app\index.js:376:39)
    at C:\Users\Blond\AppData\Roaming\npm\node_modules\generator-angular-cordova\node_modules\yeoman-generator\lib\base.js:341:43
    at C:\Users\Blond\AppData\Roaming\npm\node_modules\generator-angular-cordova\node_modules\yeoman-generator\node_modules\async\lib\a
sync.js:551:21
    at C:\Users\Blond\AppData\Roaming\npm\node_modules\generator-angular-cordova\node_modules\yeoman-generator\node_modules\async\lib\a
sync.js:227:13
    at iterate (C:\Users\Blond\AppData\Roaming\npm\node_modules\generator-angular-cordova\node_modules\yeoman-generator\node_modules\as
ync\lib\async.js:134:13)
    at C:\Users\Blond\AppData\Roaming\npm\node_modules\generator-angular-cordova\node_modules\yeoman-generator\node_modules\async\lib\a
sync.js:145:25
    at C:\Users\Blond\AppData\Roaming\npm\node_modules\generator-angular-cordova\node_modules\yeoman-generator\node_modules\async\lib\a
sync.js:229:17
    at C:\Users\Blond\AppData\Roaming\npm\node_modules\generator-angular-cordova\node_modules\yeoman-generator\node_modules\async\lib\a
sync.js:556:34
    at C:\Users\Blond\AppData\Roaming\npm\node_modules\generator-angular-cordova\node_modules\yeoman-generator\lib\base.js:327:11

Any idea? index.html is missing.

Thanks

**Comment by 529** [comment]
hi, I'm also the same phenomenon.

```
$ yo angular-cordova
...
[?] Which modules would you like to include? angular-resource.js, angular-cookies.js, angular-sanitize.js

/Users/529/.nodebrew/node/v0.11.11/lib/node_modules/generator-angular-cordova/node_modules/yeoman-generator/lib/actions/actions.js:194
throw new Error('Unable to read "' + filepath + '" file (Error code: ' + e
            ^
            Error: Unable to read "/Users/529/.nodebrew/node/v0.11.11/lib/node_modules/generator-angular-cordova/templates/common/index.html" file (Error code: ENOENT).
            at Generator.read (/Users/529/.nodebrew/node/v0.11.11/lib/node_modules/generator-angular-cordova/node_modules/yeoman-generator/lib/actions/actions.js:194:11)
            at Generator.readIndex (/Users/529/.nodebrew/node/v0.11.11/lib/node_modules/generator-angular-cordova/app/index.js:376:39)
            at /Users/529/.nodebrew/node/v0.11.11/lib/node_modules/generator-angular-cordova/node_modules/yeoman-generator/lib/base.js:341:43
            at /Users/529/.nodebrew/node/v0.11.11/lib/node_modules/generator-angular-cordova/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
            at /Users/529/.nodebrew/node/v0.11.11/lib/node_modules/generator-angular-cordova/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
            at iterate (/Users/529/.nodebrew/node/v0.11.11/lib/node_modules/generator-angular-cordova/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
            at /Users/529/.nodebrew/node/v0.11.11/lib/node_modules/generator-angular-cordova/node_modules/yeoman-generator/node_modules/async/lib/async.js:145:25
            at /Users/529/.nodebrew/node/v0.11.11/lib/node_modules/generator-angular-cordova/node_modules/yeoman-generator/node_modules/async/lib/async.js:229:17
            at /Users/529/.nodebrew/node/v0.11.11/lib/node_modules/generator-angular-cordova/node_modules/yeoman-generator/node_modules/async/lib/async.js:556:34
            at /Users/529/.nodebrew/node/v0.11.11/lib/node_modules/generator-angular-cordova/node_modules/yeoman-generator/lib/base.js:327:11
```

index.html is missing.

Thanks.

**Comment by fadzlan** [comment]
Same thing here with me, when I checked, the whole template folder was non-existent

**Comment by bmwertman** [comment]
Same thing here

**Comment by rfryca** [comment]
npm install -g generator-angular-cordova does not install all necessary files and directories.
there is only app folder inside generator-angular-cordova in your node modules global repository  folder. 

You can clone repository https://github.com/wangshijun/generator-angular-cordova.git into '/Users/529/.nodebrew/node/v0.11.11/lib/node_modules/generator-angular-cordova' or other place where you have your generator-angular-cordova module installed

This will create all necessary files (including templates/common/index.html)

**Comment by project707** [comment]
This is broken for me as well.

And the above hack did not work for me since it needs exact paths (doesn't just search for the files) and you can't just clone overwriting the original directory. All I can guess it that these file dependencies are missing from the installed generator-angular-cordova module right now, and this just needs to be fixed.

**Comment by gerbsen** [comment]
its broke for me too, but cloning the repo at the specific location did the trick
