### ISSUE TITLE
Issue at the end of scaffolding

### ISSUE THREAD

**Issue by mitchmalone** [wangshijun/generator-angular-cordova#3]
Mitch:platform mitch$ yo angular-cordova

Out of the box I include Ionic and some AngularJS recommended modules.

? What is the name of your app? (Spaces aren't allowed) progressr
? What would you like the package to be? com.progressr
? What platforms would you like to add support for? iOS
? What plugins would you like to include by default? 
? Would you like to copy some sample icons for cordova? Yes
Creating cordova app: progressr
Adding requested platforms to the Cordova project...

✔  added ios
Installing the Cordova plugins...
no plugin selected
? Would you like to use Sass (with Compass)? No
? Would you like to include Ionic: Yes
? Which modules would you like to include? angular-resource.js, angular-cookies.js, angular-sanitize.js
   create www/css/main.css
   create www/index.html
   create bower.json
   create package.json
   create .bowerrc
   create .jshintrc
   create .editorconfig
   create Gruntfile.js
   create www/img/ionic.png
   create www/img/yeoman.png
   create www/res/icons/ios/icon-57-2x.png
   create www/res/icons/ios/icon-57.png
   create www/res/icons/ios/icon-72-2x.png
   create www/res/icons/ios/icon-72.png
   create www/res/screens/ios/screen-ipad-landscape-2x.png
   create www/res/screens/ios/screen-ipad-landscape.png
   create www/res/screens/ios/screen-ipad-portrait-2x.png
   create www/res/screens/ios/screen-ipad-portrait.png
   create www/res/screens/ios/screen-iphone-landscape-2x.png
   create www/res/screens/ios/screen-iphone-landscape.png
   create www/res/screens/ios/screen-iphone-portrait-2x.png
   create www/res/screens/ios/screen-iphone-portrait-568h-2x.png
   create www/res/screens/ios/screen-iphone-portrait.png

I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.

   invoke   karma:app
   invoke       angular-cordova:common
   create         test/.jshintrc
   create         test/runner.html
   create         www/.buildignore
   create         www/404.html
   create         www/favicon.ico
   create         www/tpl/about.html
   create         www/tpl/detail.html
   create         www/tpl/form.html
   create         www/tpl/index.html
   create         www/tpl/tabs.html
   create         .gitignore
   invoke       angular-cordova:main
   create         www/js/app.js
   invoke       angular-cordova:controller

/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/lockfile/lockfile.js:46
      throw er
            ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at Generator.generateSourceAndTest (/usr/local/lib/node_modules/generator-angular-cordova/script-base.js:91:28)
    at Generator.createControllerFiles (/usr/local/lib/node_modules/generator-angular-cordova/controller/index.js:19:10)
    at /usr/local/lib/node_modules/yeoman-generator/lib/base.js:407:16
    at processImmediate [as _immediateCallback](timers.js:345:15)
Mitch:platform mitch$

**Comment by mitchmalone** [comment]
@wangshijun Do you have any idea how I might fix this?

**Comment by Mart-Bogdan** [comment]
I have the same error
npm@2.9.1
node@0.12.3
